name: Test source code

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: go install github.com/vektra/mockery/v2@v2.20.0

      - name: Build
        run: go build -v ./...

      - name: Generate test mocks
        run: go generate ./...

      - name: Test
        run: go test -v ./...
